// ─── Provider Config Management ───────────────────────────────
// Store and manage real WireGuard provider configurations
// persists to localStorage so configs survive page reloads

import { useState, useCallback, useEffect } from "react";

export interface ProviderConfig {
  id: string;
  name: string;
  provider: string; // "mullvad" | "protonvpn" | "windscribe" | "ivpn" | "custom"
  serverName: string;
  city: string;
  country: string;
  wgEndpoint: string; // IP:port or hostname:port
  serverPublicKey: string;
  clientPrivateKey: string;
  clientIp: string;
  dns: string;
  mtu: number;
  active: boolean;
  createdAt: number;
}

const STORAGE_KEY = "velocityvpn_providers";

function loadProviders(): ProviderConfig[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

function saveProviders(providers: ProviderConfig[]) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(providers));
}

export function useProviderConfig() {
  const [providers, setProviders] = useState<ProviderConfig[]>(loadProviders);
  const [activeProvider, setActiveProvider] = useState<ProviderConfig | null>(
    () => {
      const all = loadProviders();
      return all.find((p) => p.active) || null;
    }
  );

  useEffect(() => {
    saveProviders(providers);
  }, [providers]);

  const addProvider = useCallback((config: Omit<ProviderConfig, "id" | "createdAt">) => {
    const newProvider: ProviderConfig = {
      ...config,
      id: `provider_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
      createdAt: Date.now(),
    };
    setProviders((prev) => [...prev, newProvider]);
    return newProvider;
  }, []);

  const removeProvider = useCallback((id: string) => {
    setProviders((prev) => prev.filter((p) => p.id !== id));
    setActiveProvider((prev) => (prev?.id === id ? null : prev));
  }, []);

  const activateProvider = useCallback((id: string | null) => {
    if (!id) {
      setProviders((prev) => prev.map((p) => ({ ...p, active: false })));
      setActiveProvider(null);
      return;
    }
    setProviders((prev) =>
      prev.map((p) => ({ ...p, active: p.id === id }))
    );
    const found = providers.find((p) => p.id === id) || null;
    setActiveProvider(found);
  }, [providers]);

  const updateProvider = useCallback((id: string, updates: Partial<ProviderConfig>) => {
    setProviders((prev) =>
      prev.map((p) => (p.id === id ? { ...p, ...updates } : p))
    );
    setActiveProvider((prev) =>
      prev?.id === id ? { ...prev, ...updates } : prev
    );
  }, []);

  return {
    providers,
    activeProvider,
    addProvider,
    removeProvider,
    activateProvider,
    updateProvider,
  };
}

// ─── Generate WireGuard config from provider details ──────────

export function generateProviderWireGuardConfig(p: ProviderConfig): string {
  return `# ${p.name} — ${p.city}, ${p.country}
# Provider: ${p.provider}
# Generated by VelocityVPN
[Interface]
PrivateKey = ${p.clientPrivateKey}
Address = ${p.clientIp}
DNS = ${p.dns}
MTU = ${p.mtu}

[Peer]
PublicKey = ${p.serverPublicKey}
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = ${p.wgEndpoint}
PersistentKeepalive = 25`;
}

// ─── Provider presets ─────────────────────────────────────────

export const PROVIDER_PRESETS = {
  mullvad: {
    name: "Mullvad",
    color: "#E85D4E",
    dns: "10.64.0.1",
    mtu: 1420,
    helpUrl: "https://mullvad.net/en/account/wireguard-config",
    instructions: "Go to your Mullvad account → WireGuard Config → Generate a key and select a server. Copy the IP, Public Key, and your Private Key into the fields below.",
  },
  protonvpn: {
    name: "ProtonVPN",
    color: "#6D4AFF",
    dns: "10.8.8.1",
    mtu: 1420,
    helpUrl: "https://account.protonvpn.com/downloads#wireguard",
    instructions: "Go to ProtonVPN Downloads → WireGuard → download your config. Extract the Endpoint, PublicKey, and PrivateKey from the .conf file and paste them below.",
  },
  windscribe: {
    name: "Windscribe",
    color: "#4ADE80",
    dns: "10.255.255.3",
    mtu: 1420,
    helpUrl: "https://windscribe.com/getconfig/wireguard",
    instructions: "Go to Windscribe → Get Config → WireGuard. Select a location and generate. Copy the endpoint IP, server public key, and your private key below.",
  },
  ivpn: {
    name: "IVPN",
    color: "#FBBF24",
    dns: "10.0.254.1",
    mtu: 1420,
    helpUrl: "https://www.ivpn.net/account/wireguard/",
    instructions: "Go to IVPN Account → WireGuard → generate a new key pair. Select a server and copy the endpoint, public key, and your private key into the fields.",
  },
  privado: {
    name: "PrivadoVPN",
    color: "#FF6B35",
    dns: "198.18.0.1",
    mtu: 1420,
    helpUrl: "https://privadovpn.com/setup/wireguard",
    instructions: "Log into your PrivadoVPN account → Setup → WireGuard. Select a server location and generate your config. Copy the endpoint, server public key, and your private key into the fields below.",
  },
  hideme: {
    name: "Hide.me",
    color: "#00D26A",
    dns: "10.13.1.100",
    mtu: 1420,
    helpUrl: "https://member.hide.me/en/wireguard",
    instructions: "Sign up for Hide.me (no email required) → Member Area → WireGuard. Select a server, generate your config, and copy the endpoint, server public key, and your private key into the fields below.",
  },
  custom: {
    name: "Custom / Self-Hosted",
    color: "#22D3EE",
    dns: "1.1.1.1",
    mtu: 1420,
    helpUrl: "",
    instructions: "Enter your own WireGuard server details. You'll need your server's endpoint (IP:port), your server's public key, and your client's private key.",
  },
} as const;

export type ProviderType = keyof typeof PROVIDER_PRESETS;
